# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='温度数据数据')),
                ('measure_datetime', models.DateTimeField(verbose_name='测量时间')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('demoInfo', models.CharField(blank=True, default='', max_length=128, verbose_name='其它信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measure_datetime'],
                'verbose_name_plural': '温度',
                'verbose_name': '温度',
            },
        ),
    ]
