# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='user',
        ),
    ]
