# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 08:46
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_remove_temperature_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
