# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20161125_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='headshot',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='website',
        ),
        migrations.AlterField(
            model_name='author',
            name='salutation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
