# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20161125_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
