# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20161126_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(),
        ),
    ]
