# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20161126_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
    ]
