# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_remove_book_book_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-upload_datetime']},
        ),
        migrations.AddField(
            model_name='book',
            name='upload_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上传时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='quickstart.Author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.Publisher', verbose_name='出版商'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='书名'),
        ),
    ]
