# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_auto_20161127_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='upload_datetime',
            field=models.DateTimeField(verbose_name='上传时间'),
        ),
    ]
