# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_auto_20161127_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='MLImage/%Y/%m/%d', verbose_name='作者照片'),
        ),
    ]
