# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_auto_20161128_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploader',
            name='file',
            field=models.FileField(upload_to='file/%Y%m%d', verbose_name='文件名'),
        ),
    ]
