# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0018_authordetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='时间')),
                ('localType', models.CharField(max_length=10, verbose_name='定位类型')),
                ('localTypedescription', models.CharField(max_length=50, verbose_name='定位类型说明')),
                ('latitude', models.CharField(max_length=30, verbose_name='纬度')),
                ('lontitude', models.CharField(max_length=30, verbose_name='经度')),
                ('radius', models.CharField(max_length=15, verbose_name='半径')),
                ('addr', models.CharField(max_length=100, verbose_name='地址信息')),
                ('IndoorState', models.CharField(max_length=10, verbose_name='室内状态')),
                ('locationdescribe', models.CharField(max_length=100, verbose_name='位置描述')),
            ],
            options={
                'verbose_name_plural': '地址',
                'verbose_name': '地址',
                'ordering': ['-time'],
            },
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='sex',
            field=models.IntegerField(),
        ),
    ]
