# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0019_auto_20170208_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='IndoorState',
            field=models.CharField(blank=True, max_length=10, verbose_name='室内状态'),
        ),
        migrations.AlterField(
            model_name='location',
            name='addr',
            field=models.CharField(blank=True, max_length=100, verbose_name='地址信息'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='location',
            name='localType',
            field=models.CharField(blank=True, max_length=10, verbose_name='定位类型'),
        ),
        migrations.AlterField(
            model_name='location',
            name='localTypedescription',
            field=models.CharField(blank=True, max_length=50, verbose_name='定位类型说明'),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationdescribe',
            field=models.CharField(blank=True, max_length=100, verbose_name='位置描述'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lontitude',
            field=models.CharField(blank=True, max_length=30, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='location',
            name='radius',
            field=models.CharField(blank=True, max_length=15, verbose_name='半径'),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.CharField(blank=True, max_length=50, verbose_name='时间'),
        ),
    ]
